### ISSUE TITLE
Filter for "exclude of of stock"

### ISSUE THREAD

**Issue by codewidsaurav** [nordcomputer/magento2-stockfilter#1]
i want to show filter "exclude of of stock" in layered navigation - i know this is new feature request .

can you help me for this - i will try to give you little donation for help

**Comment by ia-gaurav** [comment]
@nordcomputer  thanks a lot for waiting for it to be completed

**Comment by ia-gaurav** [comment]
i enabled module - stock filter does not shows up yet - do i need to change something in settings anywhere

**Comment by nordcomputer** [comment]
Oh, sorry - it is not finished yet - I had to start a different approach yesterday (develop branch) - Basically, I am now trying to set the attribute via cronjob. I hope, I get it working today.

**Comment by nordcomputer** [comment]
Ok, I published the first release. A cronjob runs and sets the newly created attribute `filter_stock` for each simple product. After the cronjob is done, you can filter by "In Stock: yes". I hope, that is good enough for now. You can configure the time, the cronjob shuld run (see readme file)

**Comment by ia-Gaury** [comment]
Hi,

 I added module, however its not updating Stock filter value for all the products. For some of the products its disabled which are in stock. Please check below screenshot.

![image](https://user-images.githubusercontent.com/79962372/126979146-9f6c8c87-3e63-4bee-8862-daa6fd03d07c.png)

**Comment by nordcomputer** [comment]
Are you sure, you used the latest version? The attribute in the product should look like this:
![grafik](https://user-images.githubusercontent.com/13378398/126993358-0b7746fd-c725-4d5f-915b-9689c155b74e.png)
Seems like the attribute is defined wrong (happens while the extension gets installed). You could try to go into the magento database and open the table `setup_module`. In that table, delete the line/dataset with `Nordcomputer_Stockfilter` . 
When you now run `bin/magento setup:upgrade`, the attribute gets re-created.

**Comment by ia-Gaury** [comment]
Ok. Will update the module

**Comment by nordcomputer** [comment]
Ok, after changing to another computer with a seperate develop environment, I was able to reproduce the issue. The problem was, that the attribute didnt get updated, when you run `bin/magento setup:upgrade`. I had to add a file for that. 
Afterwards I created a new release. Now! you should be fine by just upgrading the module.

Could you try, if it is working for you? @ia-Gaury @codewidsaurav @ia-gaurav

**Comment by ia-Gaury** [comment]
Hi @nordcomputer Its not working. Not showing filter on frontend.

**Comment by nordcomputer** [comment]
*Sigh - are your cronjobs running and what happens, if you set a simple product to "in stock" by hand? (The new attribute, not the default-stock attribute). May you need to reindex first?

**Comment by ia-Gaury** [comment]
Hi @nordcomputer  When I am trying to open child product from CMS its showing an error. Please check screenshot:

![image](https://user-images.githubusercontent.com/79962372/128837739-cbfa8ea1-2bea-43be-833b-633891b9a9d8.png)

**Comment by nordcomputer** [comment]
How did you install the extension? If you have installed it via zip file, you must rename the folder `magento2-stockfilter-1.0.3` to `Stockfilter`.

Then you have to go to the magento database and look into the table called `setup_module`.
Inside that table search for the line with `Nordomputer_Stockfilter` and delete that line.

Then you can run `bin/magento setup:upgrade`

If the folder is named in the wrong way, the attribute doesnt get created. I already changed that part in the readme.

**Comment by ia-gaurav** [comment]
hi @nordcomputer  module is working fine but i do face below issues

My server response time went high i had set cron time per 30 minutes - and i have around 14 k products , i checked cron code it seems to be running all simple products in loop causing issue, any way to optimize same

**Comment by nordcomputer** [comment]
hmm...that is the whole point of the extension - it iterates over all simple products and sets the attribute, depending on the stock-status. Thats because you can set the time for the cronjob by yourself (`Stores -> Configuration -> Catalog -> Inventory -> Stock Filter Cronjob Configuration`). I know, it isn't ideal, but you could set the cronjob to only run once a day (maybe at night, when there are less visitors on your page)

**Comment by ia-gaurav** [comment]
i guess instead of lopping and running cron job a single mysql can fix it , if u know db name where we need to update stock filter status

**Comment by nordcomputer** [comment]
I will have a look at it tomorrow.
I still dont know, if that could be done without harming the coding-standard, so maybe i am going to fork the extension.

**Comment by nordcomputer** [comment]
Hey @ia-gaurav,
I just created a new feature branch, where the update in the cronjob for the `stock_filter` attribute is done via a mysql-query: [feature/mysql-query](https://github.com/nordcomputer/magento2-stockfilter/tree/feature/mysql-query)

Can you test it, if it runs faster than the previous method?

**Comment by ia-gaurav** [comment]
hi @nordcomputer yest it is much faster than earlier one

**Comment by nordcomputer** [comment]
Hi @ia-gaurav,
I created a new release (v1.1).

Be aware of the new parts in the readme-file - you have to set the attribute to `in stock` at least one time for every product (old products and newly created ones), so the attribute gets created in the database for that specific product. I also added an Uninstall Script.

Just for the record: the mysql implementation was done in b7f062174eb4cd222dd41594f88ba5da79d1c360

**Comment by ia-gaurav** [comment]
hi @nordcomputer i just noticed query seems not considering - simple product of configurable products

For eg - i have A configurable product with 4 child which are set as not visible individually 

SQL query seems to update status for just 1 main configurable product, instead it should update child products
