### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by ia-gaurav** [nordcomputer/magento2-stockfilter#11]
getting below error

 Type Error occurred when creating object: Nordcomputer\Stockfilter\Cron\UpdateStockFilter, Argument 1 passed to Nordcomputer\Stockfilter\Cron\UpdateStockFilter::__construct() must implement interface Magento\Framework\App\Config\ScopeConfigInterface, instance of Magento\Catalog\Model\ResourceModel\Product\CollectionFactory given, called in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 [] []

**Comment by nordcomputer** [comment]
Hi @ia-gaurav,
can you specify, when the error occurs? And which version are you using (module & magento)? And didn't it work already at your installation, after I changed the module to use the mysql-method?

**Comment by ia-gaurav** [comment]
magento 2.4.2 i can this in my var log

**Comment by nordcomputer** [comment]
@ia-gaurav Could it be from an old version? Right now I am tailing all my magento logfiles, while the cronjob is running and I dont get any errors from my module. I assume, its in the `exception.log`?

**Comment by nordcomputer** [comment]
closed due inactivity - feel free to reopen, if error persists...
