### ISSUE TITLE
"Yes" and "No" options in navigation filter?

### ISSUE THREAD

**Issue by pabodah** [nordcomputer/magento2-stockfilter#12]
Great module :)

I want to know if it is possible to show both "Yes" and "No" as checkboxes in the layered navigation.

Requirement is to filter products with "Yes" and also with "No". 
For now seems like "Yes" is only being displayed.
![UNI711 2023-06-17 14-45-42](https://github.com/nordcomputer/magento2-stockfilter/assets/1543867/0a0f5588-85ac-4f1e-986b-c0d8a058429e)

**Comment by pabodah** [comment]
Hello,

I changed `['label' => __('No'), 'value'=> ''], ` to `['label' => __('No'), 'value'=> **0**],` in file https://github.com/nordcomputer/magento2-stockfilter/blob/main/Model/Config/Source/Options.php and seems like it fixes my issue.

![UNI711 2023-06-17 14-58-08](https://github.com/nordcomputer/magento2-stockfilter/assets/1543867/27abde9f-91eb-4adf-bb1a-b3c60ed32e35)

Thank you again for the module

**Comment by pabodah** [comment]
Hello,

I changed `['label' => __('No'), 'value'=> ''], ` to `['label' => __('No'), 'value'=> **0**],` in file https://github.com/nordcomputer/magento2-stockfilter/blob/main/Model/Config/Source/Options.php and seems like it fixes my issue.

![UNI711 2023-06-17 14-58-08](https://github.com/nordcomputer/magento2-stockfilter/assets/1543867/c639b151-47bb-400c-9926-c31b02f16cd7)


Thank you again for the module

**Comment by nordcomputer** [comment]
oh, that was too fast for me ;-) I am glad, that this extension is of some use.
@pabodah
