### ISSUE TITLE
Composer Install Error 2.4.6-p3

### ISSUE THREAD

**Issue by ghost** [nordcomputer/magento2-stockfilter#16]
After attempting to run setup:upgrade

`Deprecated Functionality: Creation of dynamic property Nordcomputer\Stockfilter\Setup\UpgradeData::$eavSetupFactory is deprecated in /var/www/html/vendor/nordcomputer/module-stockfilter/Setup/UpgradeData.php on line 19`

**Comment by nordcomputer** [comment]
Seems like I need to create a patch file instead of a setup file. I will try to fix that, when I am back at work (after my holidays).

**Comment by nordcomputer** [comment]
Happy new year @ZandaBear 

I think I got a fix for your issue. Could you test this branch?
https://github.com/nordcomputer/magento2-stockfilter/tree/bugfix/remove_obsolete_UpgradeData

Let me know, if it is working for you. If so, I will create a new release

**Comment by nordcomputer** [comment]
Happy new year @ZandaBear !

So, I coded a fix for the issue at this branch: 
https://github.com/nordcomputer/magento2-stockfilter/tree/bugfix/remove_obsolete_UpgradeData

Can you test it?
If it is working for you, I would create a new release from it
