### ISSUE TITLE
Showing an error

### ISSUE THREAD

**Issue by ia-Gaury** [nordcomputer/magento2-stockfilter#4]
Hi,
  I tried installing this module, however its showing an error. Please check screenshot:

![image](https://user-images.githubusercontent.com/79962372/126871303-e2ca6d87-a64a-441a-8436-42b00e4f824a.png)

**Comment by nordcomputer** [comment]
ah, ok - I see, what I did wrong there...Try v1.0.2 - should be fixed.

closed with Commit:  e188a40bd45e841a14b7d7290df9b19e137d9811

**Comment by ia-Gaury** [comment]
I installed your updated module, its not showing stock filter on website.
